# Exploração Inicial dos Dados

Notebook destinado a explorar os dados, buscando verificar quais as colunas presentes e a dimensão dos arquivos.

In [1]:
import os
from pathlib import Path

import pandas as pd

In [2]:
ROOT_PATH = Path(__name__).resolve().parent.parent.parent
DATA_PATH = ROOT_PATH / "nyc-tlc-data"

In [3]:
data_files = os.listdir(DATA_PATH)

In [7]:
data_files[4]

'yellow_tripdata_2022-01.parquet.gz'

In [8]:
test_df = pd.read_parquet(f"{DATA_PATH}/{data_files[4]}")

In [9]:
test_df.shape

(2463931, 19)

In [5]:
test_df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2022-01-01 00:35:40,2022-01-01 00:53:29,2.0,3.80,1.0,N,142,236,1,14.5,3.0,0.5,3.65,0.0,0.3,21.95,2.5,0.0
1,1,2022-01-01 00:33:43,2022-01-01 00:42:07,1.0,2.10,1.0,N,236,42,1,8.0,0.5,0.5,4.00,0.0,0.3,13.30,0.0,0.0
2,2,2022-01-01 00:53:21,2022-01-01 01:02:19,1.0,0.97,1.0,N,166,166,1,7.5,0.5,0.5,1.76,0.0,0.3,10.56,0.0,0.0
3,2,2022-01-01 00:25:21,2022-01-01 00:35:23,1.0,1.09,1.0,N,114,68,2,8.0,0.5,0.5,0.00,0.0,0.3,11.80,2.5,0.0
4,2,2022-01-01 00:36:48,2022-01-01 01:14:20,1.0,4.30,1.0,N,68,163,1,23.5,0.5,0.5,3.00,0.0,0.3,30.30,2.5,0.0

In [6]:
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2463931 entries, 0 to 2463930
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), str(1)
memory usage: 359.7 MB

In [7]:
test_df.shape

(2463931, 19)

In [8]:
test_df.loc[:, ['tpep_pickup_datetime', 'tpep_dropoff_datetime', 'trip_distance']].describe(include='all')

             tpep_pickup_datetime       tpep_dropoff_datetime  trip_distance
count                     2463931                     2463931   2.463931e+06
mean   2022-01-17 01:19:51.689724  2022-01-17 01:34:04.421902   5.372751e+00
min           2008-12-31 22:23:09         2008-12-31 23:06:56   0.000000e+00
25%           2022-01-09 15:37:41  2022-01-09 15:50:50.500000   1.040000e+00
50%           2022-01-17 12:11:45         2022-01-17 12:23:49   1.740000e+00
75%    2022-01-24 13:49:37.500000         2022-01-24 14:02:51   3.130000e+00
max           2022-05-18 20:41:57         2022-05-18 20:47:45   3.061593e+05
std                           NaN                         NaN   5.478714e+02

In [14]:
test_df.loc[test_df.duplicated(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime'], keep=False), ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime']].sort_values('tpep_pickup_datetime')

         VendorID tpep_pickup_datetime tpep_dropoff_datetime
1583            2  2022-01-01 00:03:22   2022-01-01 00:29:53
1582            2  2022-01-01 00:03:22   2022-01-01 00:29:53
2116            2  2022-01-01 00:07:57   2022-01-01 00:16:07
2115            2  2022-01-01 00:07:57   2022-01-01 00:16:07
3047            2  2022-01-01 00:08:41   2022-01-01 00:28:34
...           ...                  ...                   ...
2391336         2  2022-01-31 23:47:03   2022-02-01 00:17:42
2391159         2  2022-01-31 23:56:06   2022-02-01 00:03:36
2391160         2  2022-01-31 23:56:06   2022-02-01 00:03:36
2391346         2  2022-01-31 23:59:21   2022-02-01 00:05:57
2391347         2  2022-01-31 23:59:21   2022-02-01 00:05:57

[27818 rows x 3 columns]

In [9]:
test_df.VendorID.unique()

array([1, 2, 6])

In [13]:
test_df.loc[(test_df.VendorID == 2), :].duplicated().sum()

: