# Exploração Inicial dos Dados

Notebook destinado a explorar os dados, buscando verificar quais as colunas presentes e a dimensão dos arquivos.

In [1]:
import os
from pathlib import Path

import pandas as pd

In [2]:
ROOT_PATH = Path(__name__).resolve().parent.parent.parent
DATA_PATH = ROOT_PATH / "nyc-tlc-data"

In [3]:
data_files = os.listdir(DATA_PATH)

In [4]:
test_df = pd.read_parquet(f"{DATA_PATH}/{data_files[0]}")

In [5]:
test_df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2022-12-01 00:37:35,2022-12-01 00:47:35,1.0,2.00,1.0,N,170,237,1,8.5,3.00,0.5,3.10,0.0,0.3,15.40,2.5,0.00
1,1,2022-12-01 00:34:35,2022-12-01 00:55:21,0.0,8.40,1.0,N,138,141,2,26.0,4.25,0.5,0.00,0.0,0.3,31.05,2.5,1.25
2,1,2022-12-01 00:33:26,2022-12-01 00:37:34,1.0,0.80,1.0,N,140,140,1,5.0,3.00,0.5,1.76,0.0,0.3,10.56,2.5,0.00
3,1,2022-12-01 00:45:51,2022-12-01 00:53:16,1.0,3.00,1.0,N,141,79,3,10.0,3.00,0.5,0.00,0.0,0.3,13.80,2.5,0.00
4,2,2022-12-01 00:49:49,2022-12-01 00:54:13,1.0,0.76,1.0,N,261,231,1,5.0,0.50,0.5,1.76,0.0,0.3,10.56,2.5,0.00

In [6]:
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3399549 entries, 0 to 3399548
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), str(1)
memory usage: 496.3 MB

In [7]:
test_df.shape

(3399549, 19)

In [8]:
test_df.loc[:, ['tpep_pickup_datetime', 'tpep_dropoff_datetime', 'trip_distance']].describe(include='all')

             tpep_pickup_datetime       tpep_dropoff_datetime  trip_distance
count                     3399549                     3399549   3.399549e+06
mean   2022-12-15 07:31:38.939279  2022-12-15 07:49:58.661951   4.698027e+00
min           2022-11-30 19:07:12         2022-11-30 19:39:56   0.000000e+00
25%           2022-12-07 22:15:20         2022-12-07 22:31:25   1.080000e+00
50%           2022-12-14 19:30:04         2022-12-14 19:47:26   1.840000e+00
75%           2022-12-21 21:35:26         2022-12-21 21:50:31   3.600000e+00
max           2023-01-01 00:31:23         2023-01-01 23:33:40   2.227304e+05
std                           NaN                         NaN   3.506168e+02